
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-courses-s25-02
owner: ucsb-cs156-s25
repo_name: proj-courses-s25-02
pull_requests: [{"author":{"id":"U_kgDOB3DYsg","is_bot":false,"login":"evaniacheng","name":"evania"},"headRefName":"ec-classroomEndpoints","number":21,"title":"ec - modified API endpoints to get classrooms for a building","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-02/pull/21"}]
