
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-courses-s25-02
owner: ucsb-cs156-s25
repo_name: proj-courses-s25-02
pull_requests: [{"author":{"id":"MDQ6VXNlcjU5OTg4MTUw","is_bot":false,"login":"andrew200356","name":"Andrew Wang"},"headRefName":"sw-uxUpdate","number":30,"title":"sw - UX IMPROVEMENT: Make width of pagination component consistent.","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-02/pull/30"},{"author":{"id":"U_kgDOBtgnsg","is_bot":false,"login":"mujiaaa","name":"Mujia Chen"},"headRefName":"mc-add-api-for-GE","number":29,"title":"mc - Add an API Endpoint to Retrieve the List of GE Areas","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-02/pull/29"},{"author":{"id":"U_kgDOBdVC1w","is_bot":false,"login":"Elskin","name":"Xinyan Zhao"},"headRefName":"xz-jobendpoint","number":28,"title":"Xz-Paginate the Job Log Endpoint","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-02/pull/28"},{"author":{"id":"U_kgDOBXvSwA","is_bot":false,"login":"jiahuaren","name":"Jiahua Ren"},"headRefName":"jr-fixStrikerMutationSectionsTable","number":27,"title":"jr - killed all modal logic mutations in SectionsTable.js","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-02/pull/27"},{"author":{"id":"U_kgDOB3DYsg","is_bot":false,"login":"evaniacheng","name":"evania"},"headRefName":"ec-fetchClassrooms","number":26,"title":"ec - Fetched list of classrooms based on building in frontend","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-02/pull/26"},{"author":{"id":"U_kgDOCNoKew","is_bot":false,"login":"AyalaWang","name":""},"headRefName":"addDropDownMenuGEAreas","number":24,"title":"Add drop down menu ge areas","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-02/pull/24"}]
