
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-courses-s25-02
owner: ucsb-cs156-s25
repo_name: proj-courses-s25-02
pull_requests: [{"author":{"id":"U_kgDOBXvSwA","is_bot":false,"login":"jiahuaren","name":"Jiahua Ren"},"headRefName":"jr-fixStrikerMutationSectionsTable","number":27,"title":"jr - solving most stryker exceptions in SectionsTable.js except for BlockStatement return null","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-02/pull/27"},{"author":{"id":"U_kgDOB3DYsg","is_bot":false,"login":"evaniacheng","name":"evania"},"headRefName":"ec-fetchClassrooms","number":26,"title":"ec - Fetched list of classrooms based on building in frontend","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-02/pull/26"},{"author":{"id":"MDQ6VXNlcjU5OTg4MTUw","is_bot":false,"login":"andrew200356","name":"Andrew Wang"},"headRefName":"sw-weeklyView","number":25,"title":"Implement a Weekly View of Personal Schedules","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-02/pull/25"},{"author":{"id":"U_kgDOCNoKew","is_bot":false,"login":"AyalaWang","name":""},"headRefName":"addDropDownMenuGEAreas","number":24,"title":"Add drop down menu ge areas","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-02/pull/24"},{"author":{"id":"U_kgDOBtgnsg","is_bot":false,"login":"mujiaaa","name":"Mujia Chen"},"headRefName":"mc-GESearch-placeholder","number":23,"title":"mc - add placeholder page for GE search","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-02/pull/23"},{"author":{"id":"U_kgDOCNoKew","is_bot":false,"login":"AyalaWang","name":""},"headRefName":"addAPIEndpointGEareas","number":22,"title":"added api endpoint that returns the list of GE areas","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-02/pull/22"},{"author":{"id":"U_kgDOB3DYsg","is_bot":false,"login":"evaniacheng","name":"evania"},"headRefName":"ec-classroomEndpoints","number":21,"title":"ec - modified API endpoints to get classrooms for a building","url":"https://github.com/ucsb-cs156-s25/proj-courses-s25-02/pull/21"}]
